apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mainsail.fullname" . }}
  labels:
    {{- include "mainsail.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toJson | nindent 4 }}
